In [1]:
import pandas as pd

In [4]:
df=pd.read_csv(r'C:\Users\win\Downloads\archive (4)\UCI_Credit_Card.csv')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   ID                          30000 non-null  int64  
 1   LIMIT_BAL                   30000 non-null  float64
 2   SEX                         30000 non-null  int64  
 3   EDUCATION                   30000 non-null  int64  
 4   MARRIAGE                    30000 non-null  int64  
 5   AGE                         30000 non-null  int64  
 6   PAY_0                       30000 non-null  int64  
 7   PAY_2                       30000 non-null  int64  
 8   PAY_3                       30000 non-null  int64  
 9   PAY_4                       30000 non-null  int64  
 10  PAY_5                       30000 non-null  int64  
 11  PAY_6                       30000 non-null  int64  
 12  BILL_AMT1                   30000 non-null  float64
 13  BILL_AMT2                   300

In [6]:
DF1=df.drop(['SEX','EDUCATION','MARRIAGE'],axis=1)

In [7]:
x= DF1.iloc[:,1:-1].values  
y= DF1.iloc[:, -1].values 

In [8]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0) 

In [9]:
from sklearn.preprocessing import MinMaxScaler    
st_x= MinMaxScaler()    

x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)

In [11]:
import pickle
pickle.dump(st_x,open('scaling.pkl','wb'))


In [12]:
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 200, criterion="entropy")  
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=200)

In [13]:
y_pred= classifier.predict(x_test)

In [14]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)
cm

array([[5528,  340],
       [1026,  606]], dtype=int64)

In [15]:
from sklearn.metrics import accuracy_score
score =accuracy_score(y_test,y_pred)

In [16]:
score

0.8178666666666666

In [17]:
import numpy as np

In [27]:
DF1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   ID                          30000 non-null  int64  
 1   LIMIT_BAL                   30000 non-null  float64
 2   AGE                         30000 non-null  int64  
 3   PAY_0                       30000 non-null  int64  
 4   PAY_2                       30000 non-null  int64  
 5   PAY_3                       30000 non-null  int64  
 6   PAY_4                       30000 non-null  int64  
 7   PAY_5                       30000 non-null  int64  
 8   PAY_6                       30000 non-null  int64  
 9   BILL_AMT1                   30000 non-null  float64
 10  BILL_AMT2                   30000 non-null  float64
 11  BILL_AMT3                   30000 non-null  float64
 12  BILL_AMT4                   30000 non-null  float64
 13  BILL_AMT5                   300

In [18]:
data=[float(input('LIMIT_BAL')),float(input('AGE')),float(input('PAY_0')),float(input('PAY_2')),float(input('PAY_3')),float(input('PAY_4')),float(input('PAY_5')),float(input('PAY_6')),float(input('BILL_AMT1')),float(input('BILL_AMT2')),float(input('BILL_AMT3')),float(input('BILL_AMT4')),float(input('BILL_AMT5')),float(input('BILL_AMT6')),float(input('PAY_AMT1')),float(input('PAY_AMT2')),float(input('PAY_AMT3')),float(input('PAY_AMT4')),float(input('PAY_AMT5')),float(input('PAY_AMT6'))]
arr=np.array([data])

In [19]:
Data=st_x.transform(arr.reshape(1,-1))

In [20]:
classifier.predict(Data)

array([0], dtype=int64)

In [21]:
import pickle

In [22]:
pickle.dump(classifier,open('classifier.pkl','wb'))

In [23]:
pickled_model=pickle.load(open('classifier.pkl','rb'))

In [24]:
pickled_model.predict(st_x.transform(Data))

array([1], dtype=int64)